import { useEffect, useState } from 'react';
import Head from 'next/head';
import Carousel from '../components/Carousel/Carousel';
import Footer from '../components/Footer/Footer';
import Tab from '../components/Tab/Tab';
import styles from '../styles/Home.module.css';
import InfoSection from '../components/InfoSection/InfoSection';
import ModalSingIn from '../components/ModalSingIn/ModalSingIn';
import InfoSubs from '../components/InfoSubs/InfoSubs';
import clientAxios from '../config/clientAxios';

const Home = ({ galleries, queens }) => {
  const [banners, setBanners] = useState([]);

  const random = () => {
    const len = queens.length;
    return Math.floor(Math.random() * len);
  };

  useEffect(() => {
    setBanners([...banners, queens[random()]]);
  }, []);

  return (
    <div className={styles.bgHome}>
      <Head>
        <title>My Queens Club - Enjoy The Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <ModalSingIn idModal='singIn' />
        <Carousel carouselInfo={banners} />
      </header>

      <main className='mb-5'>
        <InfoSubs className='my-5' />
        <Tab galleries={galleries} queens={queens} />
        <InfoSection className="my-5" />
      </main>

      <Footer />
    </div>
  );
};

export async function getStaticProps() {
  const dataGalleries = await clientAxios('galleries');
  const galerias = dataGalleries.data;
  const dat = await clientAxios('queen');
  const reinas = dat.data;
  return {
    props: { galleries: galerias, queens: reinas },
  };
}

export default Home;
